HiQo.StaffManagement.WEB/Controllers/DepartmentController.cs
using System.Web.Mvc;
using HiQo.StaffManagement.BL.Domain.Services;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class DepartmentController : Controller
    {
        private readonly IDepartmentService _departmentService;

        public DepartmentController(IDepartmentService departmentService)
        {
            _departmentService = departmentService;
        }

        // GET: Department
        public ActionResult Index()
        {
            var listOfDepartments = _departmentService.GetAll();

            return View(listOfDepartments);
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AutoMapper;
using HiQo.StaffManagement.BL.Domain.Entities;
using HiQo.StaffManagement.BL.Domain.Services;
using HiQo.StaffManagement.Core.ViewModels;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class HomeController : Controller
    {
        private readonly IUserService _userService;

        public HomeController(IUserService userService)
        {
            _userService = userService ?? throw new ArgumentNullException(nameof(userService));
        }

        public ActionResult Index()
        { 
            var users = Mapper.Map<IEnumerable<UserDto>, IEnumerable<UserBirthdayViewModel>>(_userService.GetListOfBirthdays());
            return View(users);
        }
    }
}

HiQo.StaffManagement.WEB/Controllers/PositionController.cs
using System.Web.Mvc;
using HiQo.StaffManagement.BL.Domain.Services;

namespace HiQo.StaffManagement.WEB.Controllers
{
    public class PositionController : Controller
    {
        private readonly IPositionService _positionService;

        public PositionController(IPositionService positionService)
        {
            _positionService = positionService;
        }

        // GET: Position
        public ActionResult Index()
        {
            var listOfPositions = _positionService.GetAll();

            return View(listOfPositions);
        }
    }
}

HiQo.StaffManagement.WEB/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

HiQo.StaffManagement.WEB/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

HiQo.StaffManagement.WEB/Views/Home/Index.cshtml
@model IEnumerable<HiQo.StaffManagement.Core.ViewModels.UserBirthdayViewModel>
@{
    ViewBag.Title = "Home Page";
}
<br/>
<div class="btn-group">
    <button type="button" class="btn btn-default">@Html.ActionLink("User", "Index", "User", new {area = ""}, null)</button>
    <button type="button" class="btn btn-default">@Html.ActionLink("Departments", "Index", "Department", new {area = ""}, null)</button>
    <button type="button" class="btn btn-default">@Html.ActionLink("Positons", "Index", "Position", new {area = ""}, null)</button>
    <button type="button" class="btn btn-default">@Html.ActionLink("Map", "ShowMap", "User", new {area = ""}, null)</button>
</div>
<div class="birthday-panel">
    <div class="panel panel-default">
        <div class="panel-heading">
            <text>Happy birthday</text>
        </div>
        <div class="panel-body">
            @foreach (var user in Model)
            {
                @Html.ActionLink(user.FirstName + " " + user.LastName, "Profiles", "User", new {area = "", id = user.UserId}, null)
            }
        </div>
    </div>
</div>